/*https://convertlive.com/pt/u/converter/metros-de-newton/em/quilograma-for%C3%A7a-metros#135*/
const listaCarros = [
    {
        carro: 'byd dolphin mini 4 lugares',
        motor: 'elétrico',
        autonomia_inmetro: '280 km',
        torque_nm: '135 Nm',
        torque_kgfm: '13,7 kgfm',
        velocidade_maxima: '130 km/h',
        aceleracao_0_100: '14,9 segundos',
        tempo_de_carregamento_ac: 'não localizado no site da montadora',
        tempo_de_carregamento_dc: '30% a 80% em 30 minutos (40 kW)',
        bateria: '38 kWh',
        potencia: '75 cv',
        preco_site: 'R$118.800',
        link: 'https://www.byd.com/br/order-dolphin-mini',
    },
    {
        carro: 'byd dolphin mini 5 lugares',
        motor: 'elétrico',
        autonomia_inmetro: '280 km',
        torque_nm: '135 Nm',
        torque_kgfm: '13,7 kgfm',
        velocidade_maxima: '130 km/h',
        aceleracao_0_100: '14,9 segundos',
        tempo_de_carregamento_ac: 'não localizado no site da montadora',
        tempo_de_carregamento_dc: '30% a 80% em 30 minutos (40 kW)',
        bateria: '38 kWh',
        potencia: '75 cv',
        preco_site: 'R$122.800',
        link: 'https://www.byd.com/br/order-dolphin-mini',
    },
    {
        carro: 'byd dolphin',
        motor: 'elétrico',
        autonomia_inmetro: '291 km',
        torque_nm: '180 Nm',
        torque_kgfm: '18,3 kgfm',
        velocidade_maxima: '160 km/h',
        aceleracao_0_100: '10,9 segundos',
        tempo_de_carregamento_ac: 'não localizado no site da montadora',
        tempo_de_carregamento_dc: '30% a 80% em 30 minutos (60 kW)',
        bateria: '44,9 kWh',
        potencia: '95 cv',
        preco_site: 'R$159.800',
        link: 'https://www.byd.com/br/order-dolphin',
    },
    {
        carro: 'byd dolphin plus',
        motor: 'elétrico',
        autonomia_inmetro: '330 km',
        torque_nm: '310 Nm',
        torque_kgfm: '31,6 kgfm',
        velocidade_maxima: '160 km/h',
        aceleracao_0_100: '7 segundos',
        tempo_de_carregamento_ac: 'não localizado no site da montadora',
        tempo_de_carregamento_dc: '30% a 80% em 30 minutos (80 kW)',
        bateria: '60,48 kWh',
        potencia: '204 cv',
        preco_site: 'R$184.800',
        link: 'https://www.byd.com/br/order-dolphin-plus',
    },
    {
        carro: 'byd han',
        motor: 'elétrico',
        autonomia_inmetro: '349 km',
        torque_nm: '700 Nm',
        torque_kgfm: '71,3 kgfm',
        velocidade_maxima: '186 km/h',
        aceleracao_0_100: '3,9 segundos',
        tempo_de_carregamento_ac: 'não localizado no site da montadora',
        tempo_de_carregamento_dc: '30% a 80% em 48 minutos (120 kW)',
        bateria: '85,4 kWh',
        potencia: '517 cv',
        preco_site: 'R$559.800',
        link: 'https://www.byd.com/br/order-han-ev',
    },
    {
        carro: 'byd seal',
        motor: 'elétrico',
        autonomia_inmetro: '372 km',
        torque_nm: '590 Nm',
        torque_kgfm: '60,1 kgfm',
        velocidade_maxima: '180 km/h',
        aceleracao_0_100: '3,8 segundos',
        tempo_de_carregamento_ac: 'não localizado no site da montadora',
        tempo_de_carregamento_dc: '30% a 80% em 30 minutos (- kW)',
        bateria: '82,56 kWh',
        potencia: '531 cv',
        preco_site: 'R$299.800',
        link: 'https://www.byd.com/br/order-seal',
    },
    {
        carro: 'byd tan',
        motor: 'elétrico',
        autonomia_inmetro: '430 km',
        torque_nm: '700 Nm',
        torque_kgfm: '71,3 kgfm',
        velocidade_maxima: '190 km/h',
        aceleracao_0_100: '4,9 segundos',
        tempo_de_carregamento_ac: 'não localizado no site da montadora',
        tempo_de_carregamento_dc: '30% a 80% em 30 minutos (110-170 kW)',
        bateria: '108,8 kWh',
        potencia: '517 cv',
        preco_site: 'R$536.800',
        link: 'https://www.byd.com/br/order-tan',
    },
    {
        carro: 'byd yuan plus',
        motor: 'elétrico',
        autonomia_inmetro: '294 km',
        torque_nm: '310 Nm',
        torque_kgfm: '31,6 kgfm',
        velocidade_maxima: '160 km/h',
        aceleracao_0_100: '7,3 segundos',
        tempo_de_carregamento_ac: 'não localizado no site da montadora',
        tempo_de_carregamento_dc: '30% a 80% em 30 minutos (80 kw)',
        bateria: '60,48 kWh',
        potencia: '204 cv',
        preco_site: 'R$235.800',
        link: 'https://www.byd.com/br/order-yuan-plus',
    },
    {
        carro: 'byd yuan pro',
        motor: 'elétrico',
        autonomia_inmetro: '250 km',
        torque_nm: '290 Nm',
        torque_kgfm: '29,5 kgfm',
        velocidade_maxima: '160 km/h',
        aceleracao_0_100: '7,9 segundos',
        tempo_de_carregamento_ac: 'não localizado no site da montadora',
        tempo_de_carregamento_dc: '30% a 80% em 29 minutos (60 kW)',
        bateria: '45,1 kWh',
        potencia: '177 cv',
        preco_site: 'R$182.800',
        link: 'https://www.byd.com/br/order-yuan-pro',
    },
    {
        carro: 'gwm ora 3 skin',
        motor: 'elétrico',
        autonomia_inmetro: '232 km',
        torque_nm: '250 Nm',
        torque_kgfm: '25,5 kgfm',
        velocidade_maxima: '160 km/h',
        aceleracao_0_100: '8,2 segundos',
        tempo_de_carregamento_ac: '15% a 100% em 3 horas (11 kW)',
        tempo_de_carregamento_dc: '30% a 80% em 30 minutos (64 kW)',
        bateria: '48 kWh',
        potencia: '171 cv',
        preco_site: 'R$169.000',
        link: 'https://www.gwmmotors.com.br/pt/modelos/ora-03-skin',
    },
    {
        carro: 'gwm ora 3 gt',
        motor: 'elétrico',
        autonomia_inmetro: '319 km',
        torque_nm: '250 Nm',
        torque_kgfm: '25,5 kgfm',
        velocidade_maxima: '160 km/h',
        aceleracao_0_100: '8,2 segundos',
        tempo_de_carregamento_ac: '15% a 100% em 5 horas (11 kW)',
        tempo_de_carregamento_dc: '30% a 80% em 40 minutos (67 kW)',
        bateria: '63 kWh',
        potencia: '171 cv',
        preco_site: 'R$199.000',
        link: 'https://www.gwmmotors.com.br/pt/modelos/ora-03-gt',
    },
    {
        carro: 'neta aya',
        motor: 'elétrico',
        autonomia_inmetro: 'km',
        torque_nm: 'Nm',
        torque_kgfm: 'kgfm',
        velocidade_maxima: 'km/h',
        aceleracao_0_100: 's',
        tempo_de_carregamento_ac: '',
        tempo_de_carregamento_dc: 'h',
        bateria: 'kWh',
        potencia: 'cv',
        preco_site: 'R$',
        link: '',
    },
    {
        carro: 'neta x',
        motor: 'elétrico',
        autonomia_inmetro: 'km',
        torque_nm: 'Nm',
        torque_kgfm: 'kgfm',
        velocidade_maxima: 'km/h',
        aceleracao_0_100: 's',
        tempo_de_carregamento_ac: '',
        tempo_de_carregamento_dc: 'h',
        bateria: 'kWh',
        potencia: 'cv',
        preco_site: 'R$',
        link: '',
    },
    {
        carro: 'caoachery icar',
        motor: 'elétrico',
        autonomia_inmetro: '197 km',
        torque_nm: '150 Nm',
        torque_kgfm: '15,3 kgfm',
        velocidade_maxima: '100 km/h',
        aceleracao_0_100: '12,8 segundos',
        tempo_de_carregamento_ac: '0 a 100% em 11 horas (220v)',
        tempo_de_carregamento_dc: '80% em 36 minutos (50 kWh)',
        bateria: '30,8 kWh',
        potencia: '61 cv',
        preco_site: 'R$119.990',
        link: 'https://caoachery.com.br/icar',
    },
    {
        carro: 'renault kwid e-tech',
        motor: 'elétrico',
        autonomia_inmetro: '185 km',
        torque_nm: '113 Nm',
        torque_kgfm: '11,5 kgfm',
        velocidade_maxima: '130 km/h',
        aceleracao_0_100: '14,6 segundos',
        tempo_de_carregamento_ac: `
    <br>15% a 80% em 2 horas e 54 minutos (7,4 kW) ou<br> 
    8 horas e 57 minutos (2,2 kW)
    `,
        tempo_de_carregamento_dc: '15% a 80% 40 minutos (30 kW)',
        bateria: '26,8 kWh',
        potencia: '65 cv',
        preco_site: 'R$139.990',
        link: 'https://www.renault.com.br/veiculos-eletricos/kwid-etech.html',
    },
    {
        carro: 'renault megane e-tech',
        motor: 'elétrico',
        autonomia_inmetro: '337 km',
        torque_nm: '301 Nm',
        torque_kgfm: '30,6 kgfm',
        velocidade_maxima: '160 km/h',
        aceleracao_0_100: '7,4 segundos',
        tempo_de_carregamento_ac: `
    <br>15% a 80% em 1 hora e 50 minutos (22 kW) ou<br>
    4 horas e 10 minutos (11 kW) ou<br>
    6 horas e 1 minuto (7 kW)
    `,
        tempo_de_carregamento_dc: '15% a 80% em 36 minutos (130 kW)',
        bateria: '60 kWh',
        potencia: '220 cv',
        preco_site: 'R$279.900',
        link: 'https://www.renault.com.br/veiculos-eletricos/megane-e-tech.html',
    },
    {
        carro: 'peugeot e-2008',
        motor: 'elétrico',
        autonomia_inmetro: '261 km',
        torque_nm: '260 Nm',
        torque_kgfm: '26,5 kgfm',
        velocidade_maxima: '150 km/h',
        aceleracao_0_100: '8,9 segundos',
        tempo_de_carregamento_ac: `
    <br>0 a 80% em 6 horas e 2 minutos (7 kw - 22 kW) ou<br>
    24 horas e 56 minutos (tomada 220v)`,
        tempo_de_carregamento_dc: `
    <br>0 a 80% em 30 minutos (100 kW) ou<br>
    53 minutos (50 kw)
    `,
        bateria: '54 kWh',
        potencia: '158 cv',
        preco_site: 'R$259.990',
        link: 'https://carros.peugeot.com.br/gama/peugeot-e2008.html',
    },
    {
        carro: 'volvo ex30 single motor',
        motor: 'elétrico',
        autonomia_inmetro: '250 km',
        torque_nm: '343 Nm',
        torque_kgfm: '34,9 kgfm',
        velocidade_maxima: '180 km/h',
        aceleracao_0_100: '5,7 segundos',
        tempo_de_carregamento_ac: '0 a 100% em 6 horas (11 kW)',
        tempo_de_carregamento_dc: '10% a 80% em 26 minutos (150 kW)',
        bateria: '51 kWh',
        potencia: '272 cv',
        preco_site: 'R$229.950',
        link: 'https://www.volvocars.com/br/cars/ex30-electric/',
    },
    {
        carro: 'volvo ex30 single motor extended range',
        motor: 'elétrico',
        autonomia_inmetro: '338 km',
        torque_nm: '343 Nm',
        torque_kgfm: '34,9 kgfm',
        velocidade_maxima: '180 km/h',
        aceleracao_0_100: '5,3 segundos',
        tempo_de_carregamento_ac: '0 a 100% em 8 horas (11 kW)',
        tempo_de_carregamento_dc: '10% a 80% em 28 minutos (150 kW)',
        bateria: '69 kWh',
        potencia: '272 cv',
        preco_site: 'R$269.950',
        link: 'https://www.volvocars.com/br/cars/ex30-electric/',
    },
    {
        carro: 'jac e-js1',
        motor: 'elétrico',
        autonomia_inmetro: '181km',
        torque_nm: '150Nm',
        torque_kgfm: '15,3 kgfm',
        velocidade_maxima: '110 km/h',
        aceleracao_0_100: '10,7 s',
        tempo_de_carregamento_ac: `
    <br>0 a 80% ac wall box 4 horas e 10 minutos (6 kW) ou<br>
    8 horas e 20 minutos (3 kW)<br>
    20% a 100% ac cabo portátil em 10 horas (3 kW a 6 kW) ou<br>
    0 a 100% ac cabo portátil em 12 horas e 30 minutos (3 kW a 6 kW)
    `,
        tempo_de_carregamento_dc: `
    <br>0 a 100% em 1 hora e 30 minutos (3 kW a 6 kW) ou<br>
    0 a 80% em 1 hora e 15 minutos (3 kW a 6 kW)
    `,
        bateria: '30 kWh',
        potencia: '62 cv',
        preco_site: 'R$132.900',
        link: 'https://www.jacmotors.com.br/veiculos/eletricos-detalhes/e-js1_24_25',
    },
    {
        carro: 'hyundai ioniq 5',
        motor: 'elétrico',
        autonomia_inmetro: '347 km',
        torque_nm: '605 Nm',
        torque_kgfm: '61,6 kgfm',
        velocidade_maxima: '185 km/h',
        aceleracao_0_100: '5,3 segundos',
        tempo_de_carregamento_ac: '10% a 100% em 7 horas e 20 minutos (10,9 kW)',
        tempo_de_carregamento_dc: '10% a 80% em 18 minutos (350 kW)',
        bateria: '84 kWh',
        potencia: '325 cv',
        preco_site: 'R$409.990',
        link: 'https://www.hyundai.com.br/monte-o-seu.html?utm_source=GOOGLE&utm_medium=SEARCH&utm_campaign=HMB_ONGOING_RETAIL_IONIQ_INTENTION_LEADS_2024&utm_content=TEXT_IONIQ_SIGNATURE_PR_394990_SC_IONIQOPN_MSAD&gad_source=1&_gl=1*1sb1zg*_up*MQ..*_gs*MQ..&gclid=Cj0KCQjw5azABhD1ARIsAA0WFUGGhOf_I1V2EbXe8cp9F_MVtkLNlrjW6A-afqBZinXXnmLsWpo6n6kaAuIqEALw_wcB&gbraid=0AAAAADxIrKwB84ViTmNFUMW3gQkWWcCGn',
    },
    {
        carro: 'kia ev9',
        motor: 'elétrico',
        autonomia_inmetro: '434 km',
        torque_nm: '700 Nm',
        torque_kgfm: '71,3 kgfm',
        velocidade_maxima: '200 km/h',
        aceleracao_0_100: '5,3 segundos',
        tempo_de_carregamento_ac: '0 a 100% em 9 horas e 45 minutos (11 kW)',
        tempo_de_carregamento_dc: `
    <br>30% a 80% em 24 minutos (carregador de 350 kW) ou<br>
    em 83 minutos (carregador de 50 kW)
    `,
        bateria: '99,8 kWh',
        potencia: '385 cv',
        preco_site: 'R$749.990',
        link: 'https://www.kia.com.br/ev9',
    },
    {
        carro: 'kia ev5',
        motor: 'elétrico',
        autonomia_inmetro: '402km',
        torque_nm: '310 Nm',
        torque_kgfm: '31,6 kgfm',
        velocidade_maxima: '185 km/h',
        aceleracao_0_100: '8,9 segundos',
        tempo_de_carregamento_ac: `
    <br>0 a 100% em 8 horas e 10 minutos (11 kW) ou<br>
    9 horas e 40 minutos (7 kW)
    `,
        tempo_de_carregamento_dc: `
    <br>30% a 80% em 27 minutos (carregador de 360 kW) ou<br>
    em 83 minutos (carregador de 50 kW)
    `,
        bateria: '88,16 kWh',
        potencia: '217,5 cv',
        preco_site: 'R$389.990',
        link: 'https://www.kia.com.br/ev5',
    },
];
export default listaCarros;
