export type Carro = {
    carro: string,
    motor: string,
    autonomia_inmetro: string,
    torque_nm: string,
    torque_kgfm: string,
    velocidade_maxima: string,
    aceleracao_0_100: string,
    tempo_de_carregamento_ac: string,
    tempo_de_carregamento_dc: string,
    bateria: string,
    potencia: string,
    preco_site: string,
    link: string,
};
