/*https://convertlive.com/pt/u/converter/metros-de-newton/em/quilograma-for%C3%A7a-metros#135*/
const listaCarros = [
  {
    carro: 'byd dolphin mini 4 lugares',
    motor: 'elétrico',
    autonomia_inmetro: '280 km',
    torque_nm: '135 Nm',
    torque_kgfm: '13,7 kgfm',
    velocidade_maxima: '130 km/h',
    aceleracao_0_100: '14,9 segundos',
    tempo_de_carregamento: '30% a 80% 30 minutos',
    bateria: '38 kWh',
    potencia: '75 cv',
    preco_site: 'R$118.800',
    link: 'https://www.byd.com/br/order-dolphin-mini',
  },
  {
    carro: 'byd dolphin mini 5 lugares',
    motor: 'elétrico',
    autonomia_inmetro: '280 km',
    torque_nm: '135 Nm',
    torque_kgfm: '13,7 kgfm',
    velocidade_maxima: '130 km/h',
    aceleracao_0_100: '14,9 segundos',
    tempo_de_carregamento: '30% a 80% 30 minutos',
    bateria: '38 kWh',
    potencia: '75 cv',
    preco_site: 'R$122.800',
    link: 'https://www.byd.com/br/order-dolphin-mini',
  },
  {
    carro: 'byd dolphin',
    motor: 'elétrico',
    autonomia_inmetro: '291 km',
    torque_nm: '180 Nm',
    torque_kgfm: '18,3 kgfm',
    velocidade_maxima: '160 km/h',
    aceleracao_0_100: '10,9 segundos',
    tempo_de_carregamento: '30% a 80% 30 minutos',
    bateria: '44,9 kWh',
    potencia: '95 cv',
    preco_site: 'R$159.800',
    link: 'https://www.byd.com/br/order-dolphin',
  },
  {
    carro: 'byd dolphin plus',
    motor: 'elétrico',
    autonomia_inmetro: '330 km',
    torque_nm: '310 Nm',
    torque_kgfm: '31,6 kgfm',
    velocidade_maxima: '160 km/h',
    aceleracao_0_100: '7 segundos',
    tempo_de_carregamento: '30% a 80% 30 minutos',
    bateria: '60,48 kWh',
    potencia: '204 cv',
    preco_site: 'R$184.800',
    link: 'https://www.byd.com/br/order-dolphin-plus',
  },
  {
    carro: 'byd han',
    motor: 'elétrico',
    autonomia_inmetro: '349 km',
    torque_nm: '700 Nm',
    torque_kgfm: '71,3 kgfm',
    velocidade_maxima: '186 km/h',
    aceleracao_0_100: '3,9 segundos',
    tempo_de_carregamento: '30% a 80% 48 minutos',
    bateria: '85,4 kWh',
    potencia: '517 cv',
    preco_site: 'R$559.800',
    link: 'https://www.byd.com/br/order-han-ev',
  },
  {
    carro: 'byd seal',
    motor: 'elétrico',
    autonomia_inmetro: '372 km',
    torque_nm: '590 Nm',
    torque_kgfm: '60,1 kgfm',
    velocidade_maxima: '180 km/h',
    aceleracao_0_100: '3,8 segundos',
    tempo_de_carregamento: '30% a 80% 30 minutos',
    bateria: '82,56 kWh',
    potencia: '531 cv',
    preco_site: 'R$299.800',
    link: 'https://www.byd.com/br/order-seal',
  },
  {
    carro: 'byd tan',
    motor: 'elétrico',
    autonomia_inmetro: '430 km',
    torque_nm: '700 Nm',
    torque_kgfm: '71,3 kgfm',
    velocidade_maxima: '190 km/h',
    aceleracao_0_100: '4,9 segundos',
    tempo_de_carregamento: '30% a 80% 30 minutos',
    bateria: '108,8 kWh',
    potencia: '517 cv',
    preco_site: 'R$536.800',
    link: 'https://www.byd.com/br/order-tan',
  },
  {
    carro: 'byd yuan plus',
    motor: 'elétrico',
    autonomia_inmetro: '294 km',
    torque_nm: '310 Nm',
    torque_kgfm: '31,6 kgfm',
    velocidade_maxima: '160 km/h',
    aceleracao_0_100: '7,3 segundos', 
    tempo_de_carregamento: '30% a 80% 30 minutos',
    bateria: '60,48 kWh',
    potencia: '204 cv',
    preco_site: 'R$235.800',
    link: 'https://www.byd.com/br/order-yuan-plus',
  },
  {
    carro: 'byd yuan pro',
    motor: 'elétrico',
    autonomia_inmetro: '250 km',
    torque_nm: '290 Nm',
    torque_kgfm: '29,5 kgfm',
    velocidade_maxima: '160 km/h',
    aceleracao_0_100: '7,9 segundos',
    tempo_de_carregamento: '30% a 80% 29 minutos',
    bateria: '45,1 kWh',
    potencia: '177 cv',
    preco_site: 'R$182.800',
    link: 'https://www.byd.com/br/order-yuan-pro',
  },
  {
    carro: 'hyundai ioniq 5',
    motor: 'elétrico',
    autonomia_inmetro: '347 km',
    torque_nm: '605 Nm',
    torque_kgfm: '61,6 kgfm',
    velocidade_maxima: '185 km/h',
    aceleracao_0_100: '5,3 segundos', 
    tempo_de_carregamento: '10% a 80% 18 minutos',
    bateria: '84 kWh',
    potencia: '325 cv',
    preco_site: 'R$409.990',
    link: 'https://www.hyundai.com.br/monte-o-seu.html?utm_source=GOOGLE&utm_medium=SEARCH&utm_campaign=HMB_ONGOING_RETAIL_IONIQ_INTENTION_LEADS_2024&utm_content=TEXT_IONIQ_SIGNATURE_PR_394990_SC_IONIQOPN_MSAD&gad_source=1&_gl=1*1sb1zg*_up*MQ..*_gs*MQ..&gclid=Cj0KCQjw5azABhD1ARIsAA0WFUGGhOf_I1V2EbXe8cp9F_MVtkLNlrjW6A-afqBZinXXnmLsWpo6n6kaAuIqEALw_wcB&gbraid=0AAAAADxIrKwB84ViTmNFUMW3gQkWWcCGn',
  },
  {
    carro: 'kia ev9',
    motor: 'elétrico',
    autonomia_inmetro: '434 km',
    torque_nm: '700 Nm',
    torque_kgfm: '71,3 kgfm',
    velocidade_maxima: '200 km/h',
    aceleracao_0_100: '5,3 segundos',
    tempo_de_carregamento:
      '30% a 80% em 24 minutos (carregador de 350 kW) ou em 83 minutos (carregador de 50 kW)',
    bateria: '99,8 kWh',
    potencia: '385 cv',
    preco_site: 'R$749.990',
    link: 'https://www.kia.com.br/ev9',
  },
  {
    carro: 'kia ev5',
    motor: 'elétrico',
    autonomia_inmetro: '402km',
    torque_nm: '310 Nm',
    torque_kgfm: '31,6 kgfm',
    velocidade_maxima: '185 km/h',
    aceleracao_0_100: '8,9 segundos',
    tempo_de_carregamento:
      '30% a 80% em 27 minutos (carregador de 360 kW) ou em 83 minutos (carregador de 50 kW)',
    bateria: '88,16 kWh',
    potencia: '217,5 cv',
    preco_site: 'R$389.990',
    link: 'https://www.kia.com.br/ev5',
  },
  {
    carro: 'gwm ora 3 skin',
    motor: 'elétrico',
    autonomia_inmetro: '232 km',
    torque_nm: '250 Nm',
    torque_kgfm: '25,5 kgfm',
    velocidade_maxima: '160 km/h',
    aceleracao_0_100: '8,2 segundos',
    tempo_de_carregamento: '30% a 80% 30 minutos',
    bateria: '48 kWh',
    potencia: '171 cv',
    preco_site: 'R$169.000',
    link: 'https://www.mercadolivre.com.br/carros-novos/greatwall-motors/ora/03/skin/2025/?utm_source=gwmsite',
  },
  {
    carro: 'gwm ora 3 gt',
    motor: 'elétrico',
    autonomia_inmetro: '319 km',
    torque_nm: '250 Nm',
    torque_kgfm: '25,5 kgfm',
    velocidade_maxima: '160 km/h',
    aceleracao_0_100: '8,2 segundos',
    tempo_de_carregamento: '30% a 80% 40 minutos',
    bateria: '63 kWh',
    potencia: '171 cv',
    preco_site: 'R$199.000',
    link: 'https://www.mercadolivre.com.br/carros-novos/greatwall-motors/ora/03/gt/2025',
  },
  {
    carro: 'neta aya',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's', 
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'neta x',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'caoachery icar',
    motor: 'elétrico',
    autonomia_inmetro: '197 km',
    torque_nm: '150 Nm',
    torque_kgfm: '15,3 kgfm',
    velocidade_maxima: '100 km/h',
    aceleracao_0_100: '12,8 segundos',
    tempo_de_carregamento: '80% em 36 minutos (50 kWh)',
    bateria: '30,8 kWh',
    potencia: '61 cv',
    preco_site: 'R$119.990',
    link: 'https://caoachery.com.br/icar',
  },
  {
    carro: 'fiat 500e',
    motor: 'elétrico',
    autonomia_inmetro: '227 km',
    torque_nm: '220 Nm',
    torque_kgfm: '22,4 kgfm',
    velocidade_maxima: '-km/h',
    aceleracao_0_100: '9 segundos',
    tempo_de_carregamento: '80% em 35 minutos (85 kWh)',
    bateria: '- kWh',
    potencia: '118 cv',
    preco_site: 'R$214.990',
    link: 'https://500e.fiat.com.br/versoes/500e',
  },
  {
    carro: 'volkswagen id.4',
    motor: 'elétrico',
    autonomia_inmetro: '370 km',
    torque_nm: '310 Nm',
    torque_kgfm: '31,6 kgfm',
    velocidade_maxima: '160 km/h',
    aceleracao_0_100: '8,5 segundos',
    tempo_de_carregamento: '80% em 38 minutos (135 kW)',
    bateria: '77 kWh',
    potencia: '204 cv',
    preco_site:
      'Somente assinatura. Valor mensal com compra no final: R$4.990/mês',
    link: 'https://www.vwsignanddrive.com.br/ofertasvw/id-4',
  },
  {
    carro: 'volkswagen id.buzz',
    motor: 'elétrico',
    autonomia_inmetro: '337 km',
    torque_nm: '310 Nm',
    torque_kgfm: '31,6 kgfm',
    velocidade_maxima: '145 km/h',
    aceleracao_0_100: '10,2 segundos',
    tempo_de_carregamento: '5% a 80% em 30 minutos (170 kW)',
    bateria: '77 kWh',
    potencia: '204 cv',
    preco_site:
      'Somente assinatura. Valor mensal (não tem compra no final): R$8.990/mês',
    link: 'https://www.vwsignanddrive.com.br/ofertasvw/id-buzz',
  },
  {
    carro: 'renault kwid e-tech',
    motor: 'elétrico',
    autonomia_inmetro: '185 km',
    torque_nm: '113 Nm',
    torque_kgfm: '11,5 kgfm',
    velocidade_maxima: '130 km/h',
    aceleracao_0_100: '14,6 segundos',
    tempo_de_carregamento: '15% a 80% (30 kW) 40 minutos',
    bateria: '26,8 kWh',
    potencia: '65 cv',
    preco_site: 'R$139.990',
    link: 'https://www.renault.com.br/veiculos-eletricos/kwid-etech.html',
  },
  {
    carro: 'renault megane e-tech',
    motor: 'elétrico',
    autonomia_inmetro: '337 km',
    torque_nm: '301 Nm',
    torque_kgfm: '30,6 kgfm',
    velocidade_maxima: '160 km/h',
    aceleracao_0_100: '7,4 segundos', 
    tempo_de_carregamento:
      '15% a 80% em 36 minutos (85 kW até 130 kW)',
    bateria: '60 kWh',
    potencia: '220 cv',
    preco_site: 'R$279.900',
    link: 'https://www.renault.com.br/veiculos-eletricos/megane-e-tech.html',
  },
  {
    carro: 'renault kangoo e-tech',
    motor: 'elétrico',
    autonomia_inmetro: '210 km',
    torque_nm: '246 Nm',
    torque_kgfm: '25 kgfm',
    velocidade_maxima: '- km/h',
    aceleracao_0_100: '- s',
    tempo_de_carregamento: '80% em 30 minutos (80 kW)',
    bateria: '45 kWh',
    potencia: '120 cv',
    preco_site: 'R$299.390',
    link: 'https://www.renault.com.br/veiculos-eletricos/kangoo-e-tech.html',
  },
  {
    carro: 'peugeot e-2008',
    motor: 'elétrico',
    autonomia_inmetro: '261 km',
    torque_nm: '260 Nm',
    torque_kgfm: '26,5 kgfm',
    velocidade_maxima: '150 km/h',
    aceleracao_0_100: '8,9 segundos',
    tempo_de_carregamento: '-% em 30 minutos (- kW)',
    bateria: '54 kWh',
    potencia: '158 cv',
    preco_site: 'R$259.990',
    link: 'https://carros.peugeot.com.br/gama/peugeot-e2008.html',
  },
  {
    carro: 'bmw ix',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'bmw ix m60',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'bmw i7',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'bmw i4 gran coupe',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'bmw i4 m50 xdrive gran coupe',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'bmw ix3',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'bmw ix2',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'bmw ix1',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'bmw i5 m60',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'audi q6 e-tron',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'audi q8 e-tron',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'audi q8 sportback e-tron',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'audi sq8 sportback e-tron',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'audi e-tron gt quattro',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'audi rs e-tron gt',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'mercedes-benz eqe sedan',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'mercedes-benz eqa',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'mercedes-benz eqb',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'mercedes-benz eqe suv',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'mercedes-benz eqs suv',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'mercedes-benz amg eqs sedan',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'mercedes-benz amg eqe suv',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'porsche taycan',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'porsche taycan 4',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'porsche taycan 4s',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'porsche taycan gts',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'porsche taycan turbo',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'porsche taycan turbo s',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'porsche taycan turbo gt com pacote weissach',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'porsche taycan 4 cross turismo',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'porsche taycan 4s cross turismo',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'porsche taycan turbo cross turismo',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'porsche macan eletric',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'porsche macan 4 eletric',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'porsche macan 4s eletric',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'porsche macan turbo eletric',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'volvo ex90',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'volvo ex40',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'volvo ex30',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'volvo ec40',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'ford mustang mach-e',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'ford e-transit chassi',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'ford e-transit furgao',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'chevrolet equinox ev',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'chevrolet blazer ev',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'jac e-js1 city cargo',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'jac e-jv5.5',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'jac e-jv7l',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'jac e-jv12',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'jac iev-330p',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'jac e-jvcc',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'jac iev1200t',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'jac e-jt9,5',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'jac e-jt12,5',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
  {
    carro: 'mini cooper elétrico',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
     
    tempo_de_carregamento: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: 
  },
];

export default listaCarros;
