/*https://convertlive.com/pt/u/converter/metros-de-newton/em/quilograma-for%C3%A7a-metros#135*/
const listaCarros = [
  {
    carro: 'byd dolphin mini 4 lugares',
    motor: 'elétrico',
    autonomia_inmetro: '280 km',
    torque_nm: '135 Nm',
    torque_kgfm: '13,7 kgfm',
    peso_total: '1568 kg',
    peso_em_ordem_de_marcha: '1239 kg',
    velocidade_maxima: '130 km/h',
    aceleracao_0_100: '14,9 segundos',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: '30% a 80% 30 minutos',
    bateria: '38 kWh',
    potencia: '75 cv',
    preco_site: 'R$118.800',
    link: 'https://www.byd.com/br/order-dolphin-mini',
  },
  {
    carro: 'byd dolphin mini 5 lugares',
    motor: 'elétrico',
    autonomia_inmetro: '280 km',
    torque_nm: '135 Nm',
    torque_kgfm: '13,7 kgfm',
    peso_total: '1568 kg',
    peso_em_ordem_de_marcha: '1239 kg',
    velocidade_maxima: '130 km/h',
    aceleracao_0_100: '14,9 segundos',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: '30% a 80% 30 minutos',
    bateria: '38 kWh',
    potencia: '75 cv',
    preco_site: 'R$122.800',
    link: 'https://www.byd.com/br/order-dolphin-mini',
  },
  {
    carro: 'byd dolphin',
    motor: 'elétrico',
    autonomia_inmetro: '291 km',
    torque_nm: '180 Nm',
    torque_kgfm: '18,3 kgfm',
    peso_total: '1815 kg',
    peso_em_ordem_de_marcha: '1412 kg',
    velocidade_maxima: '160 km/h',
    aceleracao_0_100: '10,9 segundos',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: '30% a 80% 30 minutos',
    bateria: '44,9 kWh',
    potencia: '95 cv',
    preco_site: 'R$159.800',
    link: 'https://www.byd.com/br/order-dolphin',
  },
  {
    carro: 'byd dolphin plus',
    motor: 'elétrico',
    autonomia_inmetro: '330 km',
    torque_nm: '310 Nm',
    torque_kgfm: '31,6 kgfm',
    peso_total: '2068 kg',
    peso_em_ordem_de_marcha: '1658 kg',
    velocidade_maxima: '160 km/h',
    aceleracao_0_100: '7 segundos',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: '30% a 80% 30 minutos',
    bateria: '60,48 kWh',
    potencia: '204 cv',
    preco_site: 'R$184.800',
    link: 'https://www.byd.com/br/order-dolphin-plus',
  },
  {
    carro: 'byd han',
    motor: 'elétrico',
    autonomia_inmetro: '349 km',
    torque_nm: '700 Nm',
    torque_kgfm: '71,3 kgfm',
    peso_total: '- kg',
    peso_em_ordem_de_marcha: '2250 kg',
    velocidade_maxima: '186 km/h',
    aceleracao_0_100: '3,9 segundos',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: '30% a 80% 48 minutos',
    bateria: '85,4 kWh',
    potencia: '517 cv',
    preco_site: 'R$559.800',
    link: 'https://www.byd.com/br/order-han-ev',
  },
  {
    carro: 'byd seal',
    motor: 'elétrico',
    autonomia_inmetro: '372 km',
    torque_nm: '590 Nm',
    torque_kgfm: '60,1 kgfm',
    peso_total: '2631 kg',
    peso_em_ordem_de_marcha: '2185 kg',
    velocidade_maxima: '180 km/h',
    aceleracao_0_100: '3,8 segundos',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: '30% a 80% 30 minutos',
    bateria: '82,56 kWh',
    potencia: '531 cv',
    preco_site: 'R$299.800',
    link: 'https://www.byd.com/br/order-seal',
  },
  {
    carro: 'byd tan',
    motor: 'elétrico',
    autonomia_inmetro: '430 km',
    torque_nm: '700 Nm',
    torque_kgfm: '71,3 kgfm',
    peso_total: '3204 kg',
    peso_em_ordem_de_marcha: '2630 kg',
    velocidade_maxima: '190 km/h',
    aceleracao_0_100: '4,9 segundos',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: '30% a 80% 30 minutos',
    bateria: '108,8 kWh',
    potencia: '517 cv',
    preco_site: 'R$536.800',
    link: 'https://www.byd.com/br/order-tan',
  },
  {
    carro: 'byd yuan plus',
    motor: 'elétrico',
    autonomia_inmetro: '294 km',
    torque_nm: '310 Nm',
    torque_kgfm: '31,6 kgfm',
    peso_total: '- kg',
    peso_em_ordem_de_marcha: '1700 kg',
    velocidade_maxima: '160 km/h',
    aceleracao_0_100: '7,3 segundos',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: '30% a 80% 30 minutos',
    bateria: '60,48 kWh',
    potencia: '204 cv',
    preco_site: 'R$235.800',
    link: 'https://www.byd.com/br/order-yuan-plus',
  },
  {
    carro: 'byd yuan pro',
    motor: 'elétrico',
    autonomia_inmetro: '250 km',
    torque_nm: '290 Nm',
    torque_kgfm: '29,5 kgfm',
    peso_total: '- kg',
    peso_em_ordem_de_marcha: '1550 kg',
    velocidade_maxima: '160 km/h',
    aceleracao_0_100: '7,9 segundos',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: '30% a 80% 29 minutos', /*https://www.youtube.com/watch?v=knxB3oTzoDA&t=849s*/
    bateria: '45,1 kWh',
    potencia: '177 cv',
    preco_site: 'R$182.800',
    link: 'https://www.byd.com/br/order-yuan-pro',
  },
  {
    carro: 'hyundai ioniq 5',
    motor: 'elétrico',
    autonomia_inmetro: '347 km',
    torque_nm: '605 Nm',
    torque_kgfm: '61,6 kgfm',
    peso_total: '- kg',
    peso_em_ordem_de_marcha: '- kg',
    velocidade_maxima: '185 km/h',
    aceleracao_0_100: '5,3 segundos',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: '10% a 80% 18 minutos',
    bateria: '84 kWh',
    potencia: '325 cv',
    preco_site: 'R$409.990',
    link: 'https://www.hyundai.com.br/monte-o-seu.html?utm_source=GOOGLE&utm_medium=SEARCH&utm_campaign=HMB_ONGOING_RETAIL_IONIQ_INTENTION_LEADS_2024&utm_content=TEXT_IONIQ_SIGNATURE_PR_394990_SC_IONIQOPN_MSAD&gad_source=1&_gl=1*1sb1zg*_up*MQ..*_gs*MQ..&gclid=Cj0KCQjw5azABhD1ARIsAA0WFUGGhOf_I1V2EbXe8cp9F_MVtkLNlrjW6A-afqBZinXXnmLsWpo6n6kaAuIqEALw_wcB&gbraid=0AAAAADxIrKwB84ViTmNFUMW3gQkWWcCGn',
  },
  {
    carro: 'kia ev9',
    motor: 'elétrico',
    autonomia_inmetro: '434 km',
    torque_nm: '700 Nm',
    torque_kgfm: '71,3 kgfm',
    peso_total: '3240 kg',
    peso_em_ordem_de_marcha: '2704 kg',
    velocidade_maxima: '200 km/h',
    aceleracao_0_100: '5,3 segundos',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: '30% a 80% em 24 minutos (carregador de 350 kW) ou em 83 minutos (carregador de 50 kW)',
    bateria: '99,8 kWh',
    potencia: '385 cv',
    preco_site: 'R$749.990',
    link: 'https://www.kia.com.br/ev9',
  },
  {
    carro: 'kia ev5',
    motor: 'elétrico',
    autonomia_inmetro: '402km',
    torque_nm: '310 Nm',
    torque_kgfm: '31,6 kgfm',
    peso_total: '2530 kg',
    peso_em_ordem_de_marcha: '2141 kg',
    velocidade_maxima: '185 km/h',
    aceleracao_0_100: '8,9 segundos',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: '30% a 80% em 27 minutos (carregador de 360 kW) ou em 83 minutos (carregador de 50 kW)',
    bateria: '88,16 kWh',
    potencia: '217,5 cv',
    preco_site: 'R$389.990',
    link: 'https://www.kia.com.br/ev5',
  },
  {
    carro: 'gwm ora 3 skin',
    motor: 'elétrico',
    autonomia_inmetro: '232 km',
    torque_nm: '250 Nm',
    torque_kgfm: '25,5 kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: '1540 kg',
    velocidade_maxima: '160 km/h',
    aceleracao_0_100: '8,2 segundos', 
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: '30% a 80% 30 minutos',
    bateria: '48 kWh',
    potencia: '171 cv',
    preco_site: 'R$169.000',
    link: '',
  },
  {
    carro: 'gwm ora 3 gt',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'neta aya',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'neta x',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'caoachery icar',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'fiat 500e',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'volkswagen id.4',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'volkswagen id.buzz',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'renault kwid e-tech',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'renault megane e-tech',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'renault kangoo e-tech',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'peugeot e-2008',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'bmw ix',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'bmw ix m60',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'bmw i7',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'bmw i4 gran coupe',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'bmw i4 m50 xdrive gran coupe',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'bmw ix3',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'bmw ix2',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'bmw ix1',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'bmw i5 m60',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'audi q6 e-tron',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'audi q8 e-tron',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'audi q8 sportback e-tron',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'audi sq8 sportback e-tron',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'audi e-tron gt quattro',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'audi rs e-tron gt',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'mercedes-benz eqe sedan',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'mercedes-benz eqa',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'mercedes-benz eqb',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'mercedes-benz eqe suv',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'mercedes-benz eqs suv',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'mercedes-benz amg eqs sedan',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'mercedes-benz amg eqe suv',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'porsche taycan',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'porsche taycan 4',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'porsche taycan 4s',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'porsche taycan gts',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'porsche taycan turbo',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'porsche taycan turbo s',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'porsche taycan turbo gt com pacote weissach',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'porsche taycan 4 cross turismo',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'porsche taycan 4s cross turismo',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'porsche taycan turbo cross turismo',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'porsche macan eletric',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'porsche macan 4 eletric',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'porsche macan 4s eletric',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'porsche macan turbo eletric',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'volvo ex90',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'volvo ex40',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'volvo ex30',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'volvo ec40',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'ford mustang mach-e',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'ford e-transit chassi',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'ford e-transit furgao',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'chevrolet equinox ev',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'chevrolet blazer ev',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'jac e-js1 city cargo',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'jac e-jv5.5',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'jac e-jv7l',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'jac e-jv12',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    temde_carregamento_acpo_: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'jac iev-330p',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'jac e-jvcc',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'jac iev1200t',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'jac e-jt9,5',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
  {
    carro: 'jac e-jt12,5',
    motor: 'elétrico',
    autonomia_inmetro: 'km',
    torque_nm: 'Nm',
    torque_kgfm: 'kgfm',
    peso_total: 'kg',
    peso_em_ordem_de_marcha: 'kg',
    velocidade_maxima: 'km/h',
    aceleracao_0_100: 's',
    tempo_de_carregamento_ac: '',
    tempo_de_carregamento_dc: 'h',
    bateria: 'kWh',
    potencia: 'cv',
    preco_site: 'R$',
    link: '',
  },
];

export default listaCarros;
